# Generated by Django 2.0.5 on 2018-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_date', models.DateField(verbose_name='Report Date')),
                ('ticket_num', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Quality Entries For SOC',
                'verbose_name_plural': 'Quality Entries For SOC',
            },
        ),
    ]
