# Generated by Django 2.0.5 on 2018-06-06 05:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryNOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_date', models.DateField(verbose_name='Report Date')),
                ('finding_source', models.CharField(choices=[('--', '--------'), ('N2', 'CI/OSN2'), ('N3', 'CI/OSN3'), ('N6', 'CI/OSN6'), ('N7', 'CI/OSN7'), ('N8', 'CI/OSN8'), ('R5', 'CI/OSR5-SG'), ('R2', 'CI/OSR2-CN')], default='--', max_length=2)),
                ('ticket_num', models.CharField(max_length=30)),
                ('finding_description', models.TextField()),
                ('finding_level', models.CharField(choices=[('--', '--------'), ('Mi', 'Minor'), ('Ma', 'Major'), ('Cr', 'Critical')], default='--', max_length=2)),
                ('quality_track_measurement', models.TextField(blank=True)),
                ('acknowledge_status', models.CharField(choices=[('-', '--------'), ('A', 'Accept'), ('R', 'Reject')], default='-', max_length=1)),
                ('email_send', models.BooleanField(default=False)),
                ('quality_track_comments', models.TextField()),
                ('finding_final_status', models.CharField(choices=[('-', '--------'), ('R', 'Resolved'), ('C', 'Cancelled'), ('A', 'Assigned')], default='-', max_length=1)),
            ],
            options={
                'verbose_name': 'Quality Entries',
                'verbose_name_plural': 'Quality Entries For NOC',
            },
        ),
        migrations.CreateModel(
            name='EntrySOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_date', models.DateField(verbose_name='Report Date')),
                ('ticket_num', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Quality Entries For SOC',
                'verbose_name_plural': 'Quality Entries For SOC',
            },
        ),
        migrations.CreateModel(
            name='UserFullName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='entrynoc',
            name='finding_responsible',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'groups__name': 'NOC_Group_Members'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='EntryNOC.UserFullName'),
        ),
    ]
