# Generated by Django 2.0.5 on 2018-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryNOC', '0002_delete_entrysoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrynoc',
            name='last_modify_date',
            field=models.DateField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
