# Generated by Django 2.0.5 on 2018-06-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryNOC', '0004_auto_20180607_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynoc',
            name='finding_source',
            field=models.CharField(choices=[('--', '--------'), ('QC', 'NOC Daily QC'), ('PM', 'WAN PMA report'), ('QM', 'NOC QM'), ('DM', 'Dept. QM'), ('N2', 'CI/OSN2'), ('N3', 'CI/OSN3'), ('N6', 'CI/OSN6'), ('N7', 'CI/OSN7'), ('N8', 'CI/OSN8'), ('R5', 'CI/OSR5-SG'), ('AM', 'CI/OSR1-AM'), ('UF', 'User Feedback')], default='--', max_length=2),
        ),
        migrations.AlterField(
            model_name='entrynoc',
            name='quality_track_comments',
            field=models.TextField(blank=True),
        ),
    ]
