# Generated by Django 2.0.5 on 2018-06-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryNOC', '0005_auto_20180608_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynoc',
            name='ticket_num',
            field=models.CharField(max_length=100),
        ),
    ]
